apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
- namespace.yaml
- grafana-pvc.yaml
- grafana-deployment.yaml
- service.yaml

configMapGenerator:
- name: grafana-config
  files: [ grafana.ini ] 
- name: datasources
  files: [ provisioning/datasources/default.yaml ]
